import type {
  DocumentQueueItem,
  PartnerUnit,
  Vehicle,
} from "./types";

export const vehicles: Vehicle[] = [
  {
    id: "v-axio",
    make: "Toyota",
    model: "Axio",
    year: 2019,
    classification: "Economy",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 5,
    licensePlate: "KDA 214B",
    location: "Jomo Kenyatta International Airport (JKIA)",
    pricePerDay: 3500,
    currency: "KES",
    rating: 4.7,
    trips: 214,
    image: "econ",
    fleetSource: "internal",
    approvalStatus: "approved",
    features: ["Bluetooth", "Reverse Camera", "Fuel Efficient"],
    description: "A dependable everyday saloon, perfect for city errands and short self-drive trips.",
  },
  {
    id: "v-fielder",
    make: "Toyota",
    model: "Fielder",
    year: 2018,
    classification: "Economy",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 5,
    licensePlate: "KDB 552C",
    location: "Nairobi CBD",
    pricePerDay: 3800,
    currency: "KES",
    rating: 4.6,
    trips: 176,
    image: "econ",
    fleetSource: "partner",
    partnerName: "Nairobi Wheels Ltd",
    approvalStatus: "approved",
    features: ["Spacious Boot", "USB Charging"],
    description: "A roomy, fuel-sipping wagon favoured by families running weekend errands.",
  },
  {
    id: "v-demio",
    make: "Mazda",
    model: "Demio",
    year: 2017,
    classification: "Economy",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 4,
    licensePlate: "KDC 908D",
    location: "Nairobi CBD",
    pricePerDay: 3200,
    currency: "KES",
    rating: 4.5,
    trips: 132,
    image: "econ",
    fleetSource: "internal",
    approvalStatus: "approved",
    features: ["Compact & Easy to Park", "Bluetooth"],
    description: "Nimble and economical — ideal for solo travelers navigating city traffic.",
  },
  {
    id: "v-note",
    make: "Nissan",
    model: "Note",
    year: 2016,
    classification: "Economy",
    fuelType: "Hybrid",
    transmission: "Automatic",
    capacity: 5,
    licensePlate: "KDD 341E",
    location: "Nairobi CBD",
    pricePerDay: 3400,
    currency: "KES",
    rating: 4.5,
    trips: 98,
    image: "econ",
    fleetSource: "partner",
    partnerName: "Nairobi Wheels Ltd",
    approvalStatus: "approved",
    features: ["Hybrid Engine", "Reverse Camera"],
    description: "Fuel-sipping hybrid for everyday consumers running daily errands around town.",
  },
  {
    id: "v-harrier",
    make: "Toyota",
    model: "Harrier",
    year: 2018,
    classification: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 5,
    licensePlate: "KDE 771D",
    location: "Jomo Kenyatta International Airport (JKIA)",
    pricePerDay: 7500,
    currency: "KES",
    rating: 4.9,
    trips: 301,
    image: "suv",
    fleetSource: "internal",
    approvalStatus: "approved",
    features: ["Panoramic Roof", "Reverse Camera", "Apple CarPlay"],
    description: "A comfortable, stylish crossover — a favourite airport pickup for returning diaspora.",
  },
  {
    id: "v-cx5",
    make: "Mazda",
    model: "CX-5",
    year: 2019,
    classification: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 5,
    licensePlate: "KDF 118E",
    location: "Nairobi CBD",
    pricePerDay: 8200,
    currency: "KES",
    rating: 4.8,
    trips: 88,
    image: "suv",
    fleetSource: "partner",
    partnerName: "Rift Valley Rides",
    approvalStatus: "approved",
    features: ["All-Wheel Drive", "Premium Sound", "Leather Seats"],
    description: "Refined handling and comfort for weekend getaways or upcountry family trips.",
  },
  {
    id: "v-xtrail",
    make: "Nissan",
    model: "X-Trail",
    year: 2017,
    classification: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 7,
    licensePlate: "KDG 902F",
    location: "Mombasa Moi International Airport",
    pricePerDay: 7800,
    currency: "KES",
    rating: 4.7,
    trips: 121,
    image: "suv",
    fleetSource: "internal",
    approvalStatus: "approved",
    features: ["7-Seater", "Roof Rack", "Reverse Camera"],
    description: "Practical 7-seater for coastal road trips and family transfers with extra luggage.",
  },
  {
    id: "v-prado",
    make: "Toyota",
    model: "Land Cruiser Prado (J150)",
    year: 2016,
    classification: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    capacity: 7,
    licensePlate: "KDH 340G",
    location: "Nairobi CBD",
    pricePerDay: 12500,
    currency: "KES",
    rating: 4.9,
    trips: 54,
    image: "suv",
    fleetSource: "partner",
    partnerName: "Coastal Safari Fleet",
    approvalStatus: "pending",
    features: ["4x4 Off-Road", "Diesel Range", "Roof Rack"],
    description: "Rugged and capable — built for upcountry roads, off-road stretches, and safari transfers.",
  },
  {
    id: "v-crown",
    make: "Toyota",
    model: "Crown",
    year: 2015,
    classification: "Luxury",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 4,
    licensePlate: "KDJ 615H",
    location: "Jomo Kenyatta International Airport (JKIA)",
    pricePerDay: 14000,
    currency: "KES",
    rating: 4.9,
    trips: 64,
    image: "luxury",
    fleetSource: "internal",
    approvalStatus: "approved",
    features: ["Chauffeur Available", "Leather Interior", "Airport Meet & Greet"],
    description: "A dignified executive saloon for corporate clients and VIP airport arrivals.",
  },
  {
    id: "v-alphard",
    make: "Toyota",
    model: "Alphard",
    year: 2018,
    classification: "Luxury",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 7,
    licensePlate: "KDK 483J",
    location: "Nairobi CBD",
    pricePerDay: 18500,
    currency: "KES",
    rating: 5.0,
    trips: 47,
    image: "luxury",
    fleetSource: "partner",
    partnerName: "Prestige Motors Kenya",
    approvalStatus: "approved",
    features: ["Chauffeur Available", "Captain Seats", "Premium Sound"],
    description: "Spacious, plush, and chauffeur-driven — the choice for weddings and VIP group transfers.",
  },
  {
    id: "v-markx",
    make: "Toyota",
    model: "Mark X",
    year: 2014,
    classification: "Luxury",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 5,
    licensePlate: "KDL 907K",
    location: "Nairobi CBD",
    pricePerDay: 9500,
    currency: "KES",
    rating: 4.6,
    trips: 31,
    image: "luxury",
    fleetSource: "partner",
    partnerName: "Prestige Motors Kenya",
    approvalStatus: "pending",
    features: ["Sport Trim", "Leather Interior"],
    description: "A sharp-handling executive saloon with sporty road presence for city driving.",
  },
  {
    id: "v-noah",
    make: "Toyota",
    model: "Noah",
    year: 2015,
    classification: "Road-Trip Van",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 8,
    licensePlate: "KDM 220L",
    location: "Nairobi CBD",
    pricePerDay: 8500,
    currency: "KES",
    rating: 4.7,
    trips: 76,
    image: "van",
    fleetSource: "internal",
    approvalStatus: "approved",
    features: ["Sliding Doors", "Family Seating", "Luggage Space"],
    description: "Easy-access family van, ideal for group trips, church outings, and family reunions.",
  },
  {
    id: "v-serena",
    make: "Toyota",
    model: "Serena",
    year: 2014,
    classification: "Road-Trip Van",
    fuelType: "Petrol",
    transmission: "Automatic",
    capacity: 8,
    licensePlate: "KDN 118M",
    location: "Kisumu",
    pricePerDay: 8000,
    currency: "KES",
    rating: 4.5,
    trips: 39,
    image: "van",
    fleetSource: "partner",
    partnerName: "Lakeside Tours & Travel",
    approvalStatus: "approved",
    features: ["Group Seating", "Roof Storage"],
    description: "Reliable group van for tour operators shuttling between lakeside attractions.",
  },
  {
    id: "v-safari-tour",
    make: "Toyota",
    model: "Land Cruiser Safari (Pop-Up Roof)",
    year: 2017,
    classification: "Bus",
    fuelType: "Diesel",
    transmission: "Manual",
    capacity: 7,
    licensePlate: "KDP 615N",
    location: "Nairobi CBD",
    pricePerDay: 22000,
    currency: "KES",
    rating: 4.8,
    trips: 57,
    image: "bus",
    fleetSource: "partner",
    partnerName: "EastAfrica Group Transit",
    approvalStatus: "approved",
    features: ["Pop-Up Viewing Roof", "Guide on Request", "4x4 Off-Road"],
    description: "Purpose-built safari vehicle with a pop-up roof for game viewing on tours & safaris.",
  },
];

export const partnerUnits: PartnerUnit[] = [
  { id: "pu-1", vehicleName: "Toyota Mark X (2014)", classification: "Luxury", submittedOn: "2026-08-12", status: "pending" },
  { id: "pu-2", vehicleName: "Toyota Land Cruiser Prado J150 (2016)", classification: "SUV", submittedOn: "2026-08-14", status: "pending" },
  { id: "pu-3", vehicleName: "Toyota Land Cruiser Safari (2017)", classification: "Bus", submittedOn: "2026-07-30", status: "approved" },
  { id: "pu-4", vehicleName: "Toyota Serena (2014)", classification: "Road-Trip Van", submittedOn: "2026-07-22", status: "approved" },
  { id: "pu-5", vehicleName: "Subaru Forester (2019)", classification: "SUV", submittedOn: "2026-08-01", status: "rejected" },
];

export const documentQueue: DocumentQueueItem[] = [
  { id: "dq-1", customerName: "Amara Okonkwo", bookingRef: "BK-88421", docType: "International Passport", submittedOn: "2026-08-16", status: "pending" },
  { id: "dq-2", customerName: "James Whitfield", bookingRef: "BK-88433", docType: "Driver's License", submittedOn: "2026-08-16", status: "pending" },
  { id: "dq-3", customerName: "Grace Wanjiru", bookingRef: "BK-88397", docType: "National ID", submittedOn: "2026-08-15", status: "approved" },
  { id: "dq-4", customerName: "Liu Chen", bookingRef: "BK-88405", docType: "International Passport", submittedOn: "2026-08-15", status: "pending" },
];

export const services = [
  { title: "Self-Drive", copy: "Rent the keys and go — full-tank, well-maintained vehicles for independent travel." },
  { title: "Chauffeur-Driven", copy: "Sit back with a vetted professional driver for airport runs or full-day hire." },
  { title: "Airport Transfers", copy: "Meet & greet pickups and drop-offs at JKIA, Moi International, and regional airports." },
  { title: "Corporate Travel", copy: "Vetted executive fleets and structured mobility arrangements for businesses." },
  { title: "Family Trips", copy: "Spacious vans and SUVs built for family road trips and group outings." },
  { title: "Tours & Safaris", copy: "Purpose-built 4x4s with pop-up roofs for game drives and coastal excursions." },
  { title: "Event Transport", copy: "Bulk and high-capacity transit for weddings, conferences, and group events." },
];

export const testimonials = [
  {
    name: "Amara Okonkwo",
    segment: "Diaspora Returnee",
    quote:
      "Landed at JKIA at midnight and the Harrier was waiting, verification was quick, and the whole handoff felt effortless.",
    rating: 5,
  },
  {
    name: "David Kiptoo",
    segment: "Corporate Client",
    quote:
      "We've moved our whole executive fleet booking to Nedi Hires. Invoicing is clean and the chauffeurs are always on time.",
    rating: 5,
  },
  {
    name: "Sophie Laurent",
    segment: "Tour Group Leader",
    quote:
      "Booked a Land Cruiser with a pop-up roof for our safari group — the vehicle and guide made the trip memorable.",
    rating: 5,
  },
  {
    name: "Grace Wanjiru",
    segment: "Everyday Consumer",
    quote:
      "Rent a car for the weekend without the hassle. The subscription plan has genuinely replaced owning a second car for us.",
    rating: 4,
  },
];

export const partnerNetwork = [
  "Nairobi Wheels Ltd",
  "Rift Valley Rides",
  "Coastal Safari Fleet",
  "Prestige Motors Kenya",
  "Lakeside Tours & Travel",
  "EastAfrica Group Transit",
];

export function formatMoney(amount: number, currency: string = "KES") {
  return `${currency} ${Math.round(amount).toLocaleString()}`;
}

export function getVehicleById(id: string): Vehicle | undefined {
  return vehicles.find((v) => v.id === id);
}

export const classifications = ["Economy", "SUV", "Luxury", "Bus", "Road-Trip Van"] as const;
